# Creating 1-D arrays #

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [2]:
b=np.zeros(2)
b

array([0., 0.])

In [4]:
c=np.ones(3)
c

array([1., 1., 1.])

In [5]:
# craeting empty array with 2 elemnts
d=np.empty(2)
d

array([1., 1.])

In [7]:
#wih range of element
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [8]:
#with specific range of element
f=np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [9]:
# with range and diffenrce bw two terms
g=np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# linearly spaced arrays
h=np.linspace(0,10,num=5) #uses 5 numbers to space linearly
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
#specific data types in arrays
i=np.ones(5,dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [14]:
j=np.ones(5,dtype=np.float64)
j

array([1., 1., 1., 1., 1.])

In [3]:
#table of 5
import numpy as np
np.arange(0,55, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

# 2D Arrays #

In [13]:
import numpy as np
z=np.array([[1,2],[5,4,]])
z

array([[1, 2],
       [5, 4]])

In [12]:
b=np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [16]:
c=np.concatenate((z,b), axis=0)
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [17]:
c=np.concatenate((z,b), axis=1)
c

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 3D Arrays #

In [18]:
# making and reshaping a 3d array
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
import numpy as np

In [22]:
a=np.array([[[1,2,3,4,5],
           [4,5,6,7,8]],
          [[0,1,2,3,4,],
           [5,6,7,8,9]],
          [[0,1,2,3,4],
           [5,6,7,8,9]]])
a

array([[[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8]],

       [[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [24]:
# to determin num of dimesnions
a.ndim

3

In [25]:
b=np.array([[1,2,3,4,5],
           [6,7,8,9,0],
           [10,11,12,13,14]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [10, 11, 12, 13, 14]])

In [26]:
b.ndim

2

In [27]:
# size of an array (number of elements)
a.size

30

In [28]:
# SHAPE (dimesnsions,rows,coloumns)
a.shape

(3, 2, 5)

In [30]:
a=np.arange(9) #3*3
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
#reshape
b=a.reshape(3,3) #3*3=9
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
#convert 1d into  2d
a=np.array([1,2,3,4,5,6,7,8,9])
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a.shape

(9,)

In [35]:
#row wise
b=a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
#column wise
b=a[:,np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [37]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [38]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
a.sum()

45

In [41]:
a.mean()

5.0

# Array Functions #

In [4]:
import numpy as np

In [5]:
#sorting arrays
a=np.array([1,2,4,6,8,200,320,2.5,20.8])
a

array([  1. ,   2. ,   4. ,   6. ,   8. , 200. , 320. ,   2.5,  20.8])

In [7]:
a.sort()
a

array([  1. ,   2. ,   2.5,   4. ,   6. ,   8. ,  20.8, 200. , 320. ])

In [8]:
#concatenate
b=np.array([4,8,20,15,225,42.5,44.9,1,22])
b

array([  4. ,   8. ,  20. ,  15. , 225. ,  42.5,  44.9,   1. ,  22. ])

In [9]:
c=np.concatenate((a,b))
c

array([  1. ,   2. ,   2.5,   4. ,   6. ,   8. ,  20.8, 200. , 320. ,
         4. ,   8. ,  20. ,  15. , 225. ,  42.5,  44.9,   1. ,  22. ])

In [10]:
c.sort()
c

array([  1. ,   1. ,   2. ,   2.5,   4. ,   4. ,   6. ,   8. ,   8. ,
        15. ,  20. ,  20.8,  22. ,  42.5,  44.9, 200. , 225. , 320. ])